version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - booknest-net

  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - booknest-net

  eureka-server:
    build:
      context: ./eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - booknest-net

  api-gateway:
    build:
      context: ./api-gateway
    container_name: api-gateway
    ports:
      - "9000:9000"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - EUREKA_INSTANCE_HOSTNAME=api-gateway
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
    depends_on:
      - eureka-server
    networks:
      - booknest-net

  auth-service:
    build:
      context: ./auth-service
    container_name: auth-service
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - EUREKA_INSTANCE_HOSTNAME=auth-service
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/booknest_auth_service_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
    depends_on:
      - mysql-db
      - eureka-server
      - rabbitmq
    networks:
      - booknest-net

  book-service:
    build:
      context: ./book-service
    container_name: book-service
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - EUREKA_INSTANCE_HOSTNAME=book-service
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/booknest_book_service_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    depends_on:
      - mysql-db
      - eureka-server
    networks:
      - booknest-net

  cart-service:
    build:
      context: ./cart-service
    container_name: cart-service
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - EUREKA_INSTANCE_HOSTNAME=cart-service
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/booknest_cart_service_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    depends_on:
      - mysql-db
      - eureka-server
    networks:
      - booknest-net

  notification-service:
    build:
      context: ./notification-service
    container_name: notification-service
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - EUREKA_INSTANCE_HOSTNAME=notification-service
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/booknest_notification_service_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
    depends_on:
      - mysql-db
      - eureka-server
      - rabbitmq
    networks:
      - booknest-net

  order-service:
    build:
      context: ./order-service
    container_name: order-service
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - EUREKA_INSTANCE_HOSTNAME=order-service
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/booknest_order_service_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
    depends_on:
      - mysql-db
      - eureka-server
      - rabbitmq
    networks:
      - booknest-net

  payment-service:
    build:
      context: ./payment-service
    container_name: payment-service
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - EUREKA_INSTANCE_HOSTNAME=payment-service
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/booknest_payment_service_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    depends_on:
      - mysql-db
      - eureka-server
    networks:
      - booknest-net

  review-service:
    build:
      context: ./review-service
    container_name: review-service
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - EUREKA_INSTANCE_HOSTNAME=review-service
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/booknest_review_service_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    depends_on:
      - mysql-db
      - eureka-server
    networks:
      - booknest-net

  wallet-service:
    build:
      context: ./wallet-service
    container_name: wallet-service
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - EUREKA_INSTANCE_HOSTNAME=wallet-service
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/booknest_wallet_service_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    depends_on:
      - mysql-db
      - eureka-server
    networks:
      - booknest-net

  wishlist-service:
    build:
      context: ./wishlist-service
    container_name: wishlist-service
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - EUREKA_INSTANCE_HOSTNAME=wishlist-service
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/booknest_wishlist_service_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    depends_on:
      - mysql-db
      - eureka-server
    networks:
      - booknest-net

volumes:
  mysql_data:

networks:
  booknest-net:
    driver: bridge
